kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: ghcr-au-json-secret
  labels:
    repository: ghcr.io
    user: aubique
    app: covid19map
data:
  .dockerconfigjson: `echo "{\"auths\":{\"ghcr.io\":{\"auth\":\"$TOKEN\"}}}" | base64 -w0`
